#!/bin/bash

~/Documents/kafka_2.12-2.3.0/bin/kafka-topics.sh --delete --zookeeper localhost:2181 --topic ticks;
~/Documents/kafka_2.12-2.3.0/bin/kafka-topics.sh --delete --zookeeper localhost:2181 --topic market;

~/Documents/kafka_2.12-2.3.0/bin/zookeeper-server-stop.sh -daemon ~/Documents/kafka_2.12-2.3.0/config/zookeeper.properties;
~/Documents/kafka_2.12-2.3.0/bin/kafka-server-stop.sh -daemon ~/Documents/kafka_2.12-2.3.0/config/server.properties;
#~/Documents/kafka_2.12-2.3.0/bin/kafka-console-producer.sh --delete --broker-list localhost:9092 --topic ticks;
#~/Documents/kafka_2.12-2.3.0/bin/kafka-console-producer.sh --delete --broker-list localhost:9092 --topic market;


#~/Documents/kafka_2.12-2.3.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic ticks --from-beginning;
