#!/bin/bash

~/Documents/kafka_2.12-2.3.0/bin/zookeeper-server-start.sh -daemon ~/Documents/kafka_2.12-2.3.0/config/zookeeper.properties;
~/Documents/kafka_2.12-2.3.0/bin/kafka-server-start.sh -daemon ~/Documents/kafka_2.12-2.3.0/config/server.properties;
#~/Documents/kafka_2.12-2.3.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic ticks;
#~/Documents/kafka_2.12-2.3.0/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic ticks;
~/Documents/kafka_2.12-2.3.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic market;
~/Documents/kafka_2.12-2.3.0/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic market;

#~/Documents/kafka_2.12-2.3.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic ticks --from-beginning;
